# Changes to workflow name require changes to badge URL in README.md
name: Docker image builds

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Use native docker command within docker-compose
      COMPOSE_DOCKER_CLI_BUILD: 1
      # Use buildkit to speed up docker command
      DOCKER_BUILDKIT: 1
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ steps.extranct_branch.outputs.branch }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build full project via docker-compose
        run: |
          mv example.env .env
          sed -i 's/compdem/${{ secrets.DOCKER_USERNAME }}/g' docker-compose.yml
          docker compose build --parallel --build-arg GIT_HASH=${GITHUB_SHA:0:6}
      - name: Push images to Docker Hub
        run: docker compose push --ignore-push-failures
